
services:
  postgresql:
    image: postgres:16.4
    volumes:
      - .containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: learn-postgresql
    command: postgres -c shared_buffers=256MB -c max_connections=2000
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    container_name: learn-mysql
    volumes:
      - .containers/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: learn_db
